#!/bin/bash
xgettext --language=Python --keyword=_ --output=po/emmi-software-manager.pot usr/lib/emmi/emmi-software-manager/*.py
cd po
msgmerge es.po emmi-software-manager.pot -o es.po
msgmerge pt.po emmi-software-manager.pot -o pt.po
